services:
  discord-bot:
    build: ./ # Bot
    restart: unless-stopped
    depends_on:
      - filebrowser
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    volumes:
      - dbmb-database:/srv

volumes:
  dbmb-database: #  This is the volume for the bot's database
